jobs:
  build:
    executor:
      name: go/default
      tag: "1.15"
    steps:
      - checkout
      # - go/load-cache
      - go/mod-download
      # - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  build_image:
    docker:
    - image: docker:20.10.5
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t golang-ci .
orbs:
  go: circleci/go@1.6.0
version: 2.1
workflows:
  main:
    jobs:
      - build
      - build_image